### ISSUE TITLE
Delegate/Manager can Log In & Manage Badges

### ISSUE THREAD

**Issue by drakedanner** [FlipsideCrypto/badger#37] opened 2022-10-20 03:22 UTC
Critical feature for go live and for MetricsDAO Season 3 scaling:

- Users with the permission to manage badges on behalf of an organization need to be able to log in and view badges they control

**Comment by nftchance** [comment] 2022-10-20 04:48
Has been added to API support. We will move to front-end requirements before can be merged.

@masonchain will take over from here.

**Comment by masonchain** [comment] 2022-10-21 08:10
Duplicate of [this issue/PR](https://github.com/FlipsideCrypto/badger/pull/44)

Has been implemented, just needs merging and stress testing.

**Closed by masonchain** 2022-10-21 08:10 UTC
Labels: critical
