### ISSUE TITLE
Fix: ENS and Wallet Duplicated

### ISSUE THREAD

**Issue by forgxyz** [FlipsideCrypto/badger#55] opened 2022-10-24 23:30 UTC
This is possibly @drakedanner 's fault.
My ENS was added as a delegate which is now showing twice. Interestingly, only the line with the ENS shows Y for holder.

![image](https://user-images.githubusercontent.com/58153492/197649062-d95ef4cf-6153-458c-840c-674c6dfdd092.png)

**Comment by nftchance** [comment] 2022-10-25 02:25
Nice catch, Forg thank you! 

An issue with our indexer should be updated for you by tomorrow.

**Comment by masonchain** [comment] 2022-10-25 02:26
Thanks for the report @forgxyz. Will look into this further.

Dev Note:
- Seems like a duplicate user can be created with non checksummed addresses.
<img width="1084" alt="Screen Shot 2022-10-24 at 9 22 59 PM" src="https://user-images.githubusercontent.com/33527785/197667206-004a222c-4e85-4460-bf61-c1918b5c9236.png">
dresses.

This was caused by not check summing on the front end, so it can be addressed there. However, it might be something to check for on the back end as well.

**Comment by masonchain** [comment] 2022-10-27 21:32
Will be addressed by this issue: [#57](https://github.com/FlipsideCrypto/badger/issues/57)

**Closed by masonchain** 2022-10-27 21:32 UTC
Labels: bug
